name: Update ChatBot FAQ Data

on:
  schedule:
    - cron: '0 0 * * *'  # Chạy mỗi ngày lúc 0h UTC (7h sáng Việt Nam)
  workflow_dispatch:     # Cho phép mình chạy thủ công nếu cần

jobs:
  update-faq:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Pull latest data from Google Drive (Giả lập bước này nếu cần)
        run: |
          echo "// TODO: Chỗ này mình sẽ thêm script tự động đọc Drive nếu cần" > faqData.js
          echo "export const faqData = { 'thuế': { 'thuế thu nhập cá nhân là gì': { answer: 'Thuế TNCN là khoản tiền cá nhân phải nộp.', keywords: ['thuế', 'thu nhập', 'cá nhân'] }}};" >> faqData.js

      - name: Commit and push updated faqData.js
        run: |
          git config --global user.name 'ami-chatbot-bot'
          git config --global user.email 'ami.chatbot@bot.com'
          git add faqData.js
          git commit -m "Update faqData.js automatically [skip ci]" || echo "Nothing to commit"
          git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:main
