name: Update ChatBot FAQ Data

on:
  schedule:
    - cron: "0 3 * * *" # Hàng ngày lúc 10h sáng VN
  workflow_dispatch:

jobs:
  update-faq:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Hoặc phiên bản phù hợp

      - name: Create data directory
        run: mkdir -p ./data

      - name: Run data.js to generate faq-latest.json
        run: node data.js

      - name: Debug directory structure
        run: ls -R # Kiểm tra xem faq-latest.json có được tạo không

      - name: Update FAQ data
        run: |
          echo "Cập nhật dữ liệu FAQ tự động"
          if [ -f ./data/faq-latest.json ]; then
            cp ./data/faq-latest.json ./public/faq.json
          else
            echo "Lỗi: File faq-latest.json không tồn tại."
            exit 1
          fi

      - name: Commit and Push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git add .
          git commit -m "Auto-update ChatBot FAQ Data"
          git push https://raydoanhuy:${GH_PAT}@github.com/raydoanhuy/ami-dashboard-demo3.git main
