name: Update ChatBot FAQ Data

on:
  schedule:
    - cron: "0 3 * * *" # Hàng ngày lúc 10h sáng VN
  workflow_dispatch:

jobs:
  update-faq:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name 'raydoanhuy'
          git config --global user.email 'raydoanhuy@gmail.com'

      - name: Update FAQ data
        run: |
          echo "Cập nhật dữ liệu FAQ tự động"
          # Ví dụ cập nhật file từ Google Drive
          cp ./data/faq-latest.json ./public/faq.json

      - name: Commit and Push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git add .
          git commit -m "Auto-update ChatBot FAQ Data"
          git push https://raydoanhuy:${GH_PAT}@github.com/raydoanhuy/ami-dashboard-demo3.git main
